In [1]:
import yfinance as yf

In [2]:
msft = yf.Ticker("MSFT")

# get all stock info
msft.info

# get historical market data
hist = msft.history(period="1mo")

In [3]:
msft.history_metadata

{'currency': 'USD',
 'symbol': 'MSFT',
 'exchangeName': 'NMS',
 'fullExchangeName': 'NasdaqGS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 511108200,
 'regularMarketTime': 1718913601,
 'hasPrePostMarketData': True,
 'gmtoffset': -14400,
 'timezone': 'EDT',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 445.7,
 'fiftyTwoWeekHigh': 446.53,
 'fiftyTwoWeekLow': 441.28,
 'regularMarketDayHigh': 446.53,
 'regularMarketDayLow': 441.28,
 'regularMarketVolume': 19749057,
 'chartPreviousClose': 425.34,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EDT',
   'start': 1718956800,
   'end': 1718976600,
   'gmtoffset': -14400},
  'regular': {'timezone': 'EDT',
   'start': 1718976600,
   'end': 1719000000,
   'gmtoffset': -14400},
  'post': {'timezone': 'EDT',
   'start': 1719000000,
   'end': 1719014400,
   'gmtoffset': -14400}},
 'dataGranularity': '1d',
 'range': '1mo',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [4]:
# show actions (dividends, splits, capital gains)
msft.actions
msft.dividends
msft.splits
msft.capital_gains  # only for mutual funds & etfs

# show share count
msft.get_shares_full(start="2022-01-01", end=None)

# show financials:
# - income statement
msft.income_stmt
msft.quarterly_income_stmt
# - balance sheet
msft.balance_sheet
msft.quarterly_balance_sheet
# - cash flow statement
msft.cashflow
msft.quarterly_cashflow
# see `Ticker.get_income_stmt()` for more options

,2024-03-31,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30
Free Cash Flow,20965000000.0,9118000000.0,20666000000.0,19827000000.0,17834000000.0,NaN,NaN
Repurchase Of Capital Stock,-4213000000.0,-4000000000.0,-4831000000.0,-5704000000.0,-5509000000.0,NaN,NaN
Repayment Of Debt,-11589000000.0,-2916000000.0,-1500000000.0,-1000000000.0,0.0,NaN,NaN
Issuance Of Debt,6352000000.0,10773000000.0,25765000000.0,NaN,0.0,0.0,NaN
Issuance Of Capital Stock,522000000.0,261000000.0,685000000.0,512000000.0,536000000.0,NaN,NaN
Capital Expenditure,-10952000000.0,-9735000000.0,-9917000000.0,-8943000000.0,-6607000000.0,NaN,NaN
End Cash Position,19634000000.0,17305000000.0,80452000000.0,34704000000.0,26562000000.0,NaN,NaN
Beginning Cash Position,17305000000.0,80452000000.0,34704000000.0,26562000000.0,15646000000.0,NaN,NaN
Effect Of Exchange Rate Changes,-80000000.0,72000000.0,-99000000.0,-81000000.0,29000000.0,NaN,NaN
Changes In Cash,2409000000.0,-63219000000.0,45847000000.0,8223000000.0,10887000000.0,NaN,NaN
Financing Cash Flow,-18808000000.0,-10147000000.0,14761000000.0,-11413000000.0,-10290000000.0,NaN,NaN
Cash Flow From Continuing Financing Activities,-18808000000.0,-10147000000.0,14761000000.0,-11413000000.0,-10290000000.0,NaN,NaN
Net Other Financing Charges,-498000000.0,-201000000.0,-307000000.0,-167000000.0,-258000000.0,NaN,NaN
Cash Dividends Paid,-5572000000.0,-5574000000.0,-5051000000.0,-5054000000.0,-5059000000.0,NaN,NaN
Common Stock Dividend Paid,-5572000000.0,-5574000000.0,-5051000000.0,-5054000000.0,-5059000000.0,NaN,NaN
Net Common Stock Issuance,-3691000000.0,-3739000000.0,-4146000000.0,-5192000000.0,-4973000000.0,NaN,NaN
Common Stock Payments,-4213000000.0,-4000000000.0,-4831000000.0,-5704000000.0,-5509000000.0,NaN,NaN
Common Stock Issuance,522000000.0,261000000.0,685000000.0,512000000.0,536000000.0,NaN,NaN
Net Issuance Payments Of Debt,-9047000000.0,-633000000.0,24265000000.0,-1000000000.0,0.0,NaN,NaN
Net Short Term Debt Issuance,-3810000000.0,-8490000000.0,18692000000.0,NaN,0.0,0.0,NaN
Short Term Debt Issuance,NaN,NaN,18692000000.0,NaN,NaN,NaN,0.0
Net Long Term Debt Issuance,-5237000000.0,7857000000.0,5573000000.0,-1000000000.0,0.0,NaN,NaN
Long Term Debt Payments,-11589000000.0,-2916000000.0,-1500000000.0,-1000000000.0,0.0,NaN,NaN
Long Term Debt Issuance,6352000000.0,10773000000.0,7073000000.0,NaN,0.0,0.0,NaN
Investing Cash Flow,-10700000000.0,-71925000000.0,503000000.0,-9134000000.0,-3264000000.0,NaN,NaN
Cash Flow From Continuing Investing Activities,-10700000000.0,-71925000000.0,503000000.0,-9134000000.0,-3264000000.0,NaN,NaN
Net Other Investing Changes,-1281000000.0,1347000000.0,-982000000.0,-269000000.0,-1686000000.0,NaN,NaN
Net Investment Purchase And Sale,3108000000.0,1492000000.0,12588000000.0,419000000.0,5330000000.0,NaN,NaN
Sale Of Investment,5291000000.0,5750000000.0,21048000000.0,12395000000.0,14393000000.0,NaN,NaN
Purchase Of Investment,-2183000000.0,-4258000000.0,-8460000000.0,-11976000000.0,-9063000000.0,NaN,NaN
Net Business Purchase And Sale,-1575000000.0,-65029000000.0,-1186000000.0,-341000000.0,-301000000.0,NaN,NaN
Purchase Of Business,-1575000000.0,-65029000000.0,-1186000000.0,-341000000.0,-301000000.0,NaN,NaN
Net PPE Purchase And Sale,-10952000000.0,-9735000000.0,-9917000000.0,-8943000000.0,-6607000000.0,NaN,NaN
Purchase Of PPE,-10952000000.0,-9735000000.0,-9917000000.0,-8943000000.0,-6607000000.0,NaN,NaN
Operating Cash Flow,31917000000.0,18853000000.0,30583000000.0,28770000000.0,24441000000.0,NaN,NaN
Cash Flow From Continuing Operating Activities,31917000000.0,18853000000.0,30583000000.0,28770000000.0,24441000000.0,NaN,NaN
Change In Working Capital,2522000000.0,-10300000000.0,2418000000.0,4243000000.0,1843000000.0,NaN,NaN
Change In Other Working Capital,1977000000.0,-7092000000.0,-2701000000.0,14905000000.0,1233000000.0,NaN,NaN
Change In Other Current Liabilities,2851000000.0,1492000000.0,-3815000000.0,2864000000.0,1721000000.0,NaN,NaN
Change In Other Current Assets,-1186000000.0,-702000000.0,-2809000000.0,-3967000000.0,598000000.0,NaN,NaN
Change In Payables And Accrued Expense,648000000.0,-2521000000.0,1214000000.0,1311000000.0,-407000000.0,NaN,NaN
Change In Payable,648000000.0,-2521000000.0,1214000000.0,1311000000.0,-407000000.0,NaN,NaN
Change In Account Payable,648000000.0,-2521000000.0,1214000000.0,1311000000.0,-407000000.0,NaN,NaN
Change In Inventory,260000000.0,1474000000.0,-505000000.0,374000000.0,106000000.0,NaN,NaN
Change In Receivables,-2028000000.0,-2951000000.0,11034000000.0,-11244000000.0,-1408000000.0,NaN,NaN
Changes In Account Receivables,-2028000000.0,-2951000000.0,11034000000.0,-11244000000.0,-1408000000.0,NaN,NaN
Stock Based Compensation,2703000000.0,2828000000.0,2507000000.0,2416000000.0,2465000000.0,NaN,NaN
Deferred Tax,-1323000000.0,-1702000000.0,-568000000.0,-1888000000.0,-1675000000.0,NaN,NaN
Deferred Income Tax,-1323000000.0,-1702000000.0,-568000000.0,-1888000000.0,-1675000000.0,NaN,NaN
Depreciation Amortization Depletion,6027000000.0,5959000000.0,3921000000.0,3874000000.0,3549000000.0,NaN,NaN
Depreciation And Amortization,6027000000.0,5959000000.0,3921000000.0,3874000000.0,3549000000.0,NaN,NaN
Depreciation,6027000000.0,5959000000.0,NaN,3874000000.0,3549000000.0,3648000000.0,NaN
Operating Gains Losses,49000000.0,198000000.0,14000000.0,44000000.0,-40000000.0,NaN,NaN
Net Income From Continuing Operations,21939000000.0,21870000000.0,22291000000.0,20081000000.0,18299000000.0,NaN,NaN

In [5]:
# show holders
msft.major_holders
msft.institutional_holders
msft.mutualfund_holders
msft.insider_transactions
msft.insider_purchases
msft.insider_roster_holders

# show recommendations
msft.recommendations
msft.recommendations_summary
msft.upgrades_downgrades

                                    Firm        ToGrade   FromGrade Action
GradeDate
2024-06-17 15:50:02    Truist Securities            Buy         Buy   main
2024-06-13 20:03:26    Tigress Financial            Buy         Buy   main
2024-06-10 09:14:40  New Street Research            Buy               init
2024-06-07 12:01:58          Oppenheimer     Outperform  Outperform   main
2024-05-24 14:38:35          RBC Capital     Outperform  Outperform   reit
...                                  ...            ...         ...    ...
2012-04-20 10:18:00        Deutsche Bank            Buy               main
2012-04-03 15:53:00                  UBS            Buy               main
2012-03-22 11:03:00       Morgan Stanley     Overweight               main
2012-03-19 18:00:00       Hilliard Lyons  Long-Term Buy               main
2012-03-16 12:19:00       Argus Research            Buy        Hold     up

[693 rows x 4 columns]

In [7]:
# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
msft.isin

# show options expirations
msft.options

# show news
msft.news

[{'uuid': '305d4936-860b-374b-ac7b-2f2188074d8e',
  'title': 'is Seeking Alpha the Best Research Website for Stocks?',
  'publisher': 'Insider Monkey',
  'link': 'https://finance.yahoo.com/news/seeking-alpha-best-research-website-022225742.html',
  'providerPublishTime': 1718936545,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/3dV8Yfiz3ByTkHWtkozFsw--~B/aD00MDAwO3c9NjAwMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/insidermonkey.com/f7b3d5bf0b3c5442141341e739eacff5',
     'width': 6000,
     'height': 4000,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/0mIbU4ZD4V9sXrCOULQYTg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/insidermonkey.com/f7b3d5bf0b3c5442141341e739eacff5',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT']},
 {'uuid': 'f8606ed8-77d5-388b-bf6d-015db4dc44da',
  'title': 'As Nvidia Soars, History Advises Caution. These 12 Stocks Are Now a Safer Way to Play AI.',
  'publisher': 'Barrons.com',
  'link': 'https://finance.yahoo.com/m/f8606ed8-77d5-388b-bf6d-015db4dc44da/as-nvidia-soars%2C-history.html',
  'providerPublishTime': 1718918220,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/C8UJM5BdUtE6HjF2SmmLhQ--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/735ae6882096d3a705f2f5694143b2dc',
     'width': 1280,
     'height': 640,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/qySJ_rt9Xu9nhYf6ArT7kw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/735ae6882096d3a705f2f5694143b2dc',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA', 'MSFT', 'MU']},
 {'uuid': '25cf5418-1323-37c4-b325-a2e18b7864bf',
  'title': 'Nvidia Dips Into the Red. Microsoft Reclaims the Market Cap Title.',
  'publisher': 'Barrons.com',
  'link': 'https://finance.yahoo.com/m/25cf5418-1323-37c4-b325-a2e18b7864bf/nvidia-dips-into-the-red..html',
  'providerPublishTime': 1718916240,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/WzpgDIldr6lZpjHlonRq9w--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/5c861f06ec23797d8898f049f0ef050a',
     'width': 1280,
     'height': 640,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/cSKILxupywpKTCdaKq0lHA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/5c861f06ec23797d8898f049f0ef050a',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA', 'AMD', 'MSFT']},
 {'uuid': 'dc48e5de-fb37-3acf-9bce-e781d35d65f7',
  'title': "As Nvidia, Apple Show Cracks, This Mag 7 Lays Down AI 'Bedrock'",
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/dc48e5de-fb37-3acf-9bce-e781d35d65f7/as-nvidia%2C-apple-show-cracks%2C.html',
  'providerPublishTime': 1718915227,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/_M1XpZk6mL98CBt1aNTsLQ--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/304a7c01b2f75c0324431d5cd476f0b9',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/VsIWg6qlmshpFUjcO3PvlA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/304a7c01b2f75c0324431d5cd476f0b9',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['AMZN', 'NVDA', 'MSFT', 'META']},
 {'uuid': 'c7df9b4e-9d22-38d9-8e6e-cdd06dddf04e',
  'title': 'Dow Ends Higher As Big Tech Stocks Retreat; Nvidia Has Bad Day, But Not As Bad As A Trump Stock (Live Coverage)',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/c7df9b4e-9d22-38d9-8e6e-cdd06dddf04e/dow-ends-higher-as-big-tech.html',
  'providerPublishTime': 1718914020,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ex1OI9SIS439rieeJK.6mA--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/5e8cbf174359af44e75eb72df53d26b6',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/9aRiJSeT3OoV2AK9jErBKg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/5e8cbf174359af44e75eb72df53d26b6',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA', '^GSPC', 'MSFT', 'DELL', 'SMCI']},
 {'uuid': '1ba2856c-a3b6-3821-bf29-d66c39eebf52',
  'title': 'Nvidia: Should investors avoid the tech giant?',
  'publisher': 'Yahoo Finance Video',
  'link': 'https://finance.yahoo.com/video/nvidia-investors-avoid-tech-giant-195340932.html',
  'providerPublishTime': 1718913220,
  'type': 'VIDEO',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/8f9IGpzVNyvEU4j9qY2j9Q--~B/aD03MjA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://cf-images.us-east-1.prod.boltdns.net/v1/jit/6415665815001/848db880-6cd0-486d-b2e5-8f961791d88d/main/1280x720/4m53s792ms/match/image.jpg',
     'width': 1280,
     'height': 720,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/M1CfccGB8rXNcr74.lQQ0w--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://cf-images.us-east-1.prod.boltdns.net/v1/jit/6415665815001/848db880-6cd0-486d-b2e5-8f961791d88d/main/1280x720/4m53s792ms/match/image.jpg',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT', 'NVDA']},
 {'uuid': '8051cfa4-4e6c-3f12-9e16-c12cf6e2b90a',
  'title': 'Oracle and the AI Boom',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/8051cfa4-4e6c-3f12-9e16-c12cf6e2b90a/oracle-and-the-ai-boom.html',
  'providerPublishTime': 1718912744,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/dUM92uIlXByxXp22hXZgCQ--~B/aD0xMDgwO3c9MTkyMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/87fa64611ebcef7ca906862b9c38cdcd',
     'width': 1920,
     'height': 1080,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/ZS4gy5esfalzYxRjqB2lfw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/87fa64611ebcef7ca906862b9c38cdcd',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['ORCL', 'NVDA', 'MSFT', 'HSY', 'DOCN']},
 {'uuid': 'cbbc805c-0ead-3b0d-a8aa-1b14f833ac26',
  'title': "How Santa Clara chipmaker Nvidia became one of the world's most valuable companies in the AI boom",
  'publisher': 'LA Times',
  'link': 'https://finance.yahoo.com/news/santa-clara-chipmaker-nvidia-became-193924529.html',
  'providerPublishTime': 1718912364,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/bQCsr2XHOBzJQ31ut7uJ3A--~B/aD01NjA7dz04NDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/la_times_articles_853/06d14f84f15b6b578542b09670955f7b',
     'width': 840,
     'height': 560,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/ebGisbW.gc0HJk036WMtxw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/la_times_articles_853/06d14f84f15b6b578542b09670955f7b',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA', 'AAPL', 'MSFT']}]

In [8]:
import yfinance as yf

tickers = yf.Tickers('msft aapl goog')

# access each ticker using (example)
tickers.tickers['MSFT'].info
tickers.tickers['AAPL'].history(period="1mo")
tickers.tickers['GOOG'].actions

                           Dividends  Stock Splits
Date
2014-03-27 00:00:00-04:00        0.0      2.002000
2015-04-27 00:00:00-04:00        0.0      1.002746
2022-07-18 00:00:00-04:00        0.0     20.000000
2024-06-10 00:00:00-04:00        0.2      0.000000

In [12]:
import yfinance as yf
data = yf.download("MSFT AAPL TSLA AMZN", period="1y")

[*********************100%%**********************]  4 of 4 completed

In [13]:
print(data)

Price        Adj Close                                           Close  \
Ticker            AAPL        AMZN        MSFT        TSLA        AAPL
Date
2023-06-21  183.236404  124.830002  331.567932  259.459991  183.960007
2023-06-22  186.264435  130.149994  337.681152  264.609985  187.000000
2023-06-23  185.945694  129.330002  333.019196  256.600006  186.679993
2023-06-26  184.541229  127.330002  326.637543  241.050003  185.270004
2023-06-27  187.320251  129.179993  332.571899  250.210007  188.059998
...                ...         ...         ...         ...         ...
2024-06-13  214.240005  183.830002  441.579987  182.470001  214.240005
2024-06-14  212.490005  183.660004  442.570007  178.009995  212.490005
2024-06-17  216.669998  184.059998  448.369995  187.440002  216.669998
2024-06-18  214.289993  182.809998  446.339996  184.860001  214.289993
2024-06-20  209.679993  186.100006  445.700012  181.570007  209.679993

Price                                                 High              ...  \
Ticker            AMZN        MSFT        TSLA        AAPL        AMZN  ...
Date                                                                    ...
2023-06-21  124.830002  333.559998  259.459991  185.410004  126.730003  ...
2023-06-22  130.149994  339.709991  264.609985  187.050003  130.330002  ...
2023-06-23  129.330002  335.019989  256.600006  187.559998  130.839996  ...
2023-06-26  127.330002  328.600006  241.050003  188.050003  131.490005  ...
2023-06-27  129.179993  334.570007  250.210007  188.389999  130.089996  ...
...                ...         ...         ...         ...         ...  ...
2024-06-13  183.830002  441.579987  182.470001  216.750000  187.669998  ...
2024-06-14  183.660004  442.570007  178.009995  215.169998  183.720001  ...
2024-06-17  184.059998  448.369995  187.440002  218.949997  185.000000  ...
2024-06-18  182.809998  446.339996  184.860001  218.630005  184.289993  ...
2024-06-20  186.100006  445.700012  181.570007  214.240005  186.509995  ...

Price              Low                    Open                          \
Ticker            MSFT        TSLA        AAPL        AMZN        MSFT
Date
2023-06-21  332.070007  257.779999  184.899994  125.639999  336.369995
2023-06-22  333.339996  248.250000  183.740005  125.309998  334.119995
2023-06-23  333.450012  252.800003  185.550003  129.110001  334.359985
2023-06-26  328.489990  240.699997  186.830002  129.330002  333.720001
2023-06-27  329.299988  240.850006  185.889999  128.630005  331.859985
...                ...         ...         ...         ...         ...
2024-06-13  439.369995  181.229996  214.740005  186.089996  440.850006
2024-06-14  436.720001  176.919998  213.850006  183.080002  438.279999
2024-06-17  440.720001  177.000000  213.369995  182.520004  442.589996
2024-06-18  444.890015  182.369995  217.589996  183.740005  449.709991
2024-06-20  441.269989  179.660004  213.929993  182.910004  446.299988

Price                     Volume
Ticker            TSLA      AAPL      AMZN      MSFT       TSLA
Date
2023-06-21  275.130005  49515700  52137700  25117800  211797100
2023-06-22  250.770004  51245300  90354600  23556800  166875900
2023-06-23  259.290009  53079300  71855200  23084700  176584100
2023-06-26  250.070007  48088700  59989300  21520600  179990600
2023-06-27  243.240005  50730800  46801000  24354100  164968200
...                ...       ...       ...       ...        ...
2024-06-13  188.389999  97862700  39721500  15960600  118984100
2024-06-14  185.800003  70122700  25456400  13582000   82038200
2024-06-17  177.919998  93728300  35601900  20790000  109786100
2024-06-18  186.559998  79943300  36659200  17112500   68982300
2024-06-20  184.679993  86090700  43977300  19848600   54980600

[252 rows x 24 columns]

In [15]:
data.to_csv("info.csv")